### ISSUE TITLE
Create project structure 

### ISSUE THREAD

**Issue by vishalrangras** [chiragrangras/author-reflection-bootstrap-site#2]
- Create ./src directory in the repo
- Create ./src/html, ./src/css and ./src/js directories as well
- Create index.html, reflections.html, research.html and resources.html files in ./src/html
- Create index.css, reflections.css, research.css and resources.css files in ./src/css
- Create index.js, reflections.js, research.js and resources.js files in ./src/css

**Comment by chiragrangras** [comment]
PR has been created, I am waiting for the review.

**Comment by chiragrangras** [comment]
Code is merged.
